Added pi and e constants
Spu7Nix/SPWN-language pull request #164
Opened 2021-10-17 11:44 UTC by SpeckyYT

2021-10-17 16:31 UTC, zTags commented
very cool

2021-10-31 04:31 UTC, camila314 requested changes
e

2021-10-31 04:31 UTC, camila314 commented on libraries/std/lib.spwn
> +    e: constants.e,
one-letter variable in global space, no bueno.

2021-10-31 08:36 UTC, SpeckyYT commented
`e` got renamed to `euler` now

2021-11-05 18:55 UTC, camila314 commented
good enough

2021-11-05 18:55 UTC, merged